### ISSUE TITLE
Specify an alternate CLI name

### ISSUE THREAD

**Issue by hazmat345** [loganasherjones/yapconf#10]
* Yapcon version: 0.1.1
* Python version: 3.6.4
* Operating System: Centos 7

It would be cool if I could specify an alternate name for an option on the command line. Similar to how there's currently the ability to specify a 'short' name, but I'd like the ability to specify a different 'long' name.

To illustrate, I'd like to name an option `host`. With the environment prefix that'll end up being `BG_HOST`, which is good. I'd like to be able to have the CLI version be `bg-host` instead of just `host`.

**Comment by loganasherjones** [comment]
This is also reasonable. The only thing really left here to consider is how to handle boolean values. Boolean values that set true/false flags need to have cli names specific to their truthy/falsy values. This can make it tricky to specify the cli names, but maybe the CLI names for a boolean just need to be specified as a dictionary to map which one is a truthy and which one is falsy.
