### ISSUE TITLE
watchdog version requirement causing conflicts 

### ISSUE THREAD

**Issue by astephon88** [loganasherjones/yapconf#104]
* Yapconf version: 0.3.7
* Python version: 3.9
* Operating System: CentOS 7

### Description

The requirement for `watchdog<1` in the current stable release, which is quite an old version, is causing conflicts with other packages. It appears this problem was fixed 11 months ago in the master branch, but there has not been a new release to pypi since then. Are then any plans to cut a new release anytime soon?

**Comment by loganasherjones** [comment]
Yeah let me take a look. It's been a while since I've looked at this.

**Comment by loganasherjones** [comment]
Out of curiosity, what are you using this for?

**Comment by loganasherjones** [comment]
`1.0.0` is now released. Let me know if you have any problems.

**Comment by astephon88** [comment]
Using beergarden which has yapconf as a prereq
