### ISSUE TITLE
Multiple environment variable names

### ISSUE THREAD

**Issue by hazmat345** [loganasherjones/yapconf#13]
* Yapcon version: 0.1.1
* Python version: 3.6.4
* Operating System: Centos 7

It would be helpful to be able to specify multiple `env_name`s for a spec option. My use-case is trying to transition a current application to yapconf. I'm creating a spec option named a particular thing and I'd like to be able to set an environment variable based on yapconf's normal rules, but I also need to continue honoring the old environment variable name as well (which doesn't follow yapconf naming rules).

**Comment by loganasherjones** [comment]
This sounds mostly reasonable. If we are adding it for backwards compatibility, I think the right thing to do is to create a `previous_env_name` just to be consistent with the other way of doing it.

**Comment by loganasherjones** [comment]
The only additional work we will have to do here is to ensure that name collisions are not happening.

**Comment by loganasherjones** [comment]
Actually, collisions aren't really a problem here, so they don't need to be addressed. They'll only need to be addressed on the command-line.
