### ISSUE TITLE
Yaml dump options

### ISSUE THREAD

**Issue by hazmat345** [loganasherjones/yapconf#53]
* Yapcon version: 0.2.3
* Python version: 3.6
* Operating System: Centos7

### Description

> Describe what you were trying to get done.

I am trying to make pretty yaml files.

> Tell us what happened, what went wrong, and what you expected to happen.

I wanted them to be pretty, but they weren't.

### What I Did

I migrated a config file that was previously JSON to yaml. With pyyaml the default is to use 'flow style' (described [here](http://pyyaml.org/wiki/PyYAMLDocumentation), first FAQ).

Yes, I can just load / dump the result of the migration again with the formatting configuration I want, but that's not as nice. Also, if there are comments or formatting (I believe that ruamel tries to preserve these) they are lost. I totally understand if that's not worth the effort though.

Actually, ruamel support may be its own issue. I think they're moving to a new API where you have to construct a `YAML` object before doing anything.

**Comment by loganasherjones** [comment]
This is going to be fixed in two ways:

1. The defaults are much more sensible now when outputting the different formats. See `yapconf.dump_data` for more info
2. The dump kwargs can be passed in to `migrate_config_file` in 0.2.4
