### ISSUE TITLE
Bug in HISTORY.rst

### ISSUE THREAD

**Issue by Vestrond** [loganasherjones/yapconf#80]
Now:
line 37:
```
0.2.1 (2018-03-11)
0.2.2 (2018-03-28)
------------------
```
![image](https://user-images.githubusercontent.com/7628854/41498696-d62c4d3c-7195-11e8-9aaa-62fe04c69a7a.png)

To fix remove line 37 in HISTORY.rst.

**Comment by loganasherjones** [comment]
Thanks for the catch! Fixed in master
