### ISSUE TITLE
Generate config file without bootstrap items

### ISSUE THREAD

**Issue by hazmat345** [loganasherjones/yapconf#94]
* Yapcon version: 0.3.3
* Python version: 3.7
* Operating System: Centos 7

### Description

I'd like to be able to generate a config file and exclude bootstrap items.

My situation is this - I have 'configuration file' and 'configuration type' bootstrap items in my spec. It doesn't really make sense to have these in the configuration file itself, as they need to be specified in some other manner. So if they are present in the config file they aren't actually used.

I can already do what I want when migrating with `spec.migrate_config_file` since it has a `include_bootstrap` parameter. I'd like to avoid having to dump the config to a temp file and then migrate it.

**Comment by loganasherjones** [comment]
Hmm, I think what you're asking for is available with `migrate_config_file` You should just need to do:

`spec.migrate_config_file('/path/to/config', create=True, include_bootstrap=False)`

**Comment by hazmat345** [comment]
Yeah, but it'd be cleaner for me if I didn't have to do a 'fake' migration when I do the initial generation (paragraph in the description :smile:).

**Comment by hazmat345** [comment]
Closing as this was fixed by 5295b27d. Thanks @loganasherjones!!
